### ISSUE TITLE
Add a retriever module for DSPy

### ISSUE THREAD

**Issue by sutyum** [Technoculture/personal-graph#16]
The natural language search underlying the retriever should do the following process:
```py
def search(query: text):
  similar_nodes = search_similar_nodes(query, k=10) # user can use either top-k or filter by threshold
  similar_edges = search_similar_edges(query, k=10) # user can use either top-k or filter by threshold

  resultant_subgraph = Graph()

  resultant_subgraph.add(similar_nodes)
  for node in similar_nodes:
    resultant_subgraph.add(all_connected_nodes(node))
  for edge in similar_edges:
    resultant_subgraph.add(all_connected_nodes(edge))

  return resultant_subgraph
```

**Comment by anubhuti24** [comment]
> The natural language search underlying the retriever should do the following process:
> 
> ```python
> def search(query: text):
>   similar_nodes = search_similar_nodes(query, k=10) # user can use either top-k or filter by threshold
>   similar_edges = search_similar_edges(query, k=10) # user can use either top-k or filter by threshold
> 
>   resultant_subgraph = Graph()
> 
>   resultant_subgraph.add(similar_nodes)
>   for node in similar_nodes:
>     resultant_subgraph.add(all_connected_nodes(node))
>   for edge in similar_edges:
>     resultant_subgraph.add(all_connected_nodes(edge))
> 
>   return resultant_subgraph
> ```

Same I have implemented in search_from_graph method.
